openapi: 3.1.0
info:
  title: Highload api
  description: Highload api
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'

paths:
  /api/user/register:
    post:
      summary: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/users.yaml#/components/schemas/UserDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string